# Generated by Django 4.0.6 on 2022-08-23 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد اصلی دست بندی')),
                ('name', models.CharField(max_length=50, verbose_name='نام اصلی دست بندی')),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کلید اصلی')),
                ('name', models.CharField(max_length=50, verbose_name='نام زیر دست بندی')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='نام دست بندی')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد محصول')),
                ('name', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('count', models.SmallIntegerField(verbose_name='تعداد')),
                ('images', models.ImageField(upload_to='product/', verbose_name='عکس محصول')),
                ('amount', models.IntegerField(verbose_name='قیمت محصول')),
                ('conten', models.IntegerField(verbose_name='توضیحات')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='کالا موجود است')),
                ('is_deleted', models.BooleanField(blank=True, default=False, verbose_name='کالا موجود نیست')),
                ('categories', models.ManyToManyField(to='product.subcategory', verbose_name='دست بندی')),
            ],
        ),
    ]
